version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install dependencies needed for running tests
      - echo Installing dependencies
      - pip install -r requirements.txt

  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      #- python3 manage.py test
      - docker build -t 870314745642.dkr.ecr.eu-west-1.amazonaws.com/test-repo:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 870314745642.dkr.ecr.eu-west-1.amazonaws.com/test-repo:latest

artifacts:
  files:
    - '**/*'